/*
    This file is auto-generated by the Projucer.
    DO NOT EDIT!

    This is the header file that your files should include in order to get all the
    JUCE library headers. You should avoid including the JUCE headers directly in
    your own source files, because that wouldn't pick up the correct configuration
    options for your app.
*/

#pragma once

#define JUCE_GLOBAL_MODULE_SETTINGS_INCLUDED 1

#define JUCE_ALSA 1
#define JUCE_CONTENT_SHARING 1
#define JUCE_DIRECTSOUND 1
#define JUCE_DISABLE_CAUTIOUS_PARAMETER_ID_CHECKING 1
#define JUCE_PLUGINHOST_LADSPA 1
#define JUCE_PLUGINHOST_LV2 0
#define JUCE_PLUGINHOST_VST3 0
#define JUCE_PLUGINHOST_VST 0
#define JUCE_PLUGINHOST_ARA 0
#define JUCE_USE_CAMERA 0
#define JUCE_USE_CDBURNER 0
#define JUCE_USE_CDREADER 0
#define JUCE_USE_CURL 0
#define JUCE_USE_FLAC 0
#define JUCE_USE_OGGVORBIS 1
#define JUCE_VST3_HOST_CROSS_PLATFORM_UID 0
#define JUCE_WASAPI 1
#define JUCE_WEB_BROWSER 0
